---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-template-deploy
  namespace: ip812
  labels:
    app: go-template
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-template
  template:
    metadata:
      labels:
        app: go-template
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: go-template
          image: iypetrov/debug-display-req-headers:1.11.0
          ports:
            - containerPort: 8080
              protocol: TCP
