---
apiVersion: v1
kind: Service
metadata:
  name: go-template-svc
  namespace: ip812
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
