---
additionalArguments:
  - "--api.insecure=true"
  - "--providers.kubernetescrd"
  - "--providers.kubernetesingress"
ports:
  web:
    port: 9000
    exposedPort: 9000
    protocol: TCP
ingressRoute:
  dashboard:
    enabled: true
service:
  enabled: true
  type: ClusterIP
experimental:
  plugins:
    cloudflarewarp:
      moduleName: "github.com/BetterCorp/cloudflarewarp"
      version: "v1.3.0"
log:
  level: INFO
http:
  routers:
    traefik:
      entryPoints:
        - web
  middlewares:
    cloudflarewarp:
      plugin:
        cloudflarewarp:
          disableDefault: false
          trustip:
            - "2400:cb00::/32"
