---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: vpn
spec:
  releaseName: tailscale-operator
  interval: 10m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.84.3
      sourceRef:
        kind: HelmRepository
        name: tailscale-operator
        namespace: vpn
