---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- helmrelease.yaml
configMapGenerator:
  - name: go-template-values
    namespace: go-template 
    options:
      disableNameSuffixHash: true
    files:
      - values.yaml=../../values/go-template.yaml
