---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: go-template-creds
  namespace: doppler-operator-system
spec:
  tokenSecret: 
    name: doppler-token-secret
  project: prod
  config: prd
  managedSecret:
    name: go-template-creds
    namespace: go-template
  processors:
    PG_USERNAME:
      type: plain
      asName: username
    PG_PASSWORD:
      type: plain
      asName: password
