---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blog
  namespace: blog 
spec:
  releaseName: blog 
  interval: 1m
  chart:
    spec:
      chart: ./charts/app
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: blog-values
