---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: kubernetes
    notifications.argoproj.io/subscribe.on-sync-failed.slack: kubernetes
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: kubernetes
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ip812/apps.git
    targetRevision: main
    path: manifests/prod/argocd
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
