---
apiVersion: secrets.hashicorp.com/v1beta1
kind: HCPVaultSecretsApp
metadata:
  name: hcp-vault-secrets-app
  namespace: cloudflare
spec:
  appName: prod
  hcpAuthRef: hcp-vault/hcp-auth
  refreshAfter: 30s
  destination:
    name: hcp-vault-secrets-app
    create: true
    overwrite: true
