---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  namespace: monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd:2.4
          ports:
            - containerPort: 80
              name: http
