---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-k8s-monitoring
  namespace: monitoring
spec:
  releaseName: grafana-k8s-monitoring
  interval: 10m
  chart:
    spec:
      chart: k8s-monitoring
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: grafana-k8s-monitoring
        namespace: monitoring
  valuesFrom:
    - kind: GitRepository
      name: flux-system
      namespace: flux-system
      valuesKey: ./values/grafana-k8s-monitoring.yaml
      targetPath: .
