---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana-k8s-monitoring
  namespace: monitoring
spec:
  interval: 10m0s         
  url: https://grafana.github.io/helm-charts
