---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- secret.yaml
- helmrepository.yaml
- helmrelease.yaml
configMapGenerator:
  - name: grafana-k8s-monitoring-values
    files:
      - values.yaml=values/grafana-k8s-monitoring.yaml
