---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 80.13.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 60m
  valuesFrom:
    - kind: ConfigMap
      name: kube-prometheus-stack-values
