---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: "cloudflare/cloudflared:2025.7.0"
        args:
          - "tunnel"
          - "run"
          - "--protocol"
          - "http2"
        env:
          - name: TUNNEL_TOKEN
            valueFrom:
              secretKeyRef:
                name: cloudflared-creds
                key: TUNNEL_TOKEN
        livenessProbe:
          httpGet:
            path: /ready
            port: 20241
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
