---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: go-template
  namespace: go-template
spec:
  releaseName: go-template
  interval: 1m
  chart:
    spec:
      chart: ./charts/app
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: go-template-values
