---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: es-kb-stack
  namespace: elastic-stack
spec:
  interval: 5m
  chart:
    spec:
      chart: eck-stack
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: elastic-stack
