---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elastic-operator
  namespace: elastic-system
spec:
  interval: 5m
  chart:
    spec:
      chart: eck-operator
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: elastic-system
  valuesFrom:
    - kind: ConfigMap
      name: eck-operator-values
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: es-kb-stack
  namespace: elastic-stack
spec:
  interval: 5m
  chart:
    spec:
      chart: eck-stack
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: elastic-system
  valuesFrom:
    - kind: ConfigMap
      name: kibana-values
    - kind: ConfigMap
      name: elasticsearch-values
