---
services:
  cloudflared:
    image: cloudflare/cloudflared:2025.1.0
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${IP812_TUNNEL_TOKEN}
    networks:
      - ip812_network
    deploy:
      mode: replicated
      replicas: 3

  traefik:
    image: "traefik:v3.2"
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.websecure.forwardedHeaders.insecure=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.deviliablog.com`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - ip812_network
    deploy:
      mode: replicated
      replicas: 3

  blog:
    image: iypetrov/go-indie-hacking-starter:0.9.2
    secrets:
      - blog_domain
      - blog_port
      - blog_db_file
      - blog_aws_region
      - blog_aws_access_key_id
      - blog_aws_secret_access_key
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog.rule=Host(`deviliablog.com`)"
      - "traefik.http.routers.blog.entrypoints=web"
      - "traefik.http.services.blog.loadbalancer.server.port=8080"
    # volumes:
    #   - "/var/lib/blog/blog.db:/app/blog.db"
    #   - "/var/lib/blog/blog.db-shm:/app/blog.db-shm"
    #   - "/var/lib/blog/blog.db-wal:/app/blog.db-wal"
    networks:
      - ip812_network
    deploy:
      mode: replicated
      replicas: 3

secrets:
  blog_domain:
    external: true
  blog_port:
    external: true
  blog_db_file:
    external: true
  blog_aws_region:
    external: true
  blog_aws_access_key_id:
    external: true
  blog_aws_secret_access_key:
    external: true

networks:
  ip812_network:
    driver: overlay
    attachable: true
