---
services:
  cloudflared:
    image: cloudflare/cloudflared:2025.1.0
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    networks:
      - ip812_network
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1      
        delay: 10s          
        order: start-first  
        failure_action: rollback 
      rollback_config:
        parallelism: 1
        delay: 10s
        order: stop-first 
      restart_policy:
        condition: on-failure
        max_attempts: 3

  traefik:
    image: "traefik:v3.2"
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--experimental.plugins.cloudflarewarp.modulename=github.com/BetterCorp/cloudflarewarp"
      - "--experimental.plugins.cloudflarewarp.version=v1.3.3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.ip812.com`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.middlewares.cloudflarewarp.plugin.cloudflarewarp.disableDefault=false"
      - "traefik.http.middlewares.cloudflarewarp.plugin.cloudflarewarp.trustip.0=2400:cb00::/32"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - ip812_network
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1      
        delay: 10s          
        order: start-first  
        failure_action: rollback 
      rollback_config:
        parallelism: 1
        delay: 10s
        order: stop-first 
      restart_policy:
        condition: on-failure
        max_attempts: 3

  blog:
    image: 678468774710.dkr.ecr.eu-central-1.amazonaws.com/ip812/blog:0.39.0
    secrets:
      - blog_domain
      - blog_port
      - blog_db_file
      - blog_aws_region
      - blog_aws_access_key_id
      - blog_aws_secret_access_key
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog.rule=Host(`deviliablog.com`)"
      - "traefik.http.routers.blog.entrypoints=web"
      - "traefik.http.services.blog.loadbalancer.server.port=8080"
      - "traefik.http.services.blog.loadbalancer.healthcheck.path=/healthz"
      - "traefik.http.services.blog.loadbalancer.healthcheck.interval=10s"
    volumes:
      - blog_db:/data
    networks:
      - ip812_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1      
        delay: 10s          
        order: start-first  
        failure_action: rollback 
      rollback_config:
        parallelism: 1
        delay: 10s
        order: stop-first 
      restart_policy:
        condition: on-failure
        max_attempts: 3

secrets:
  blog_domain:
    external: true
  blog_port:
    external: true
  blog_db_file:
    external: true
  blog_aws_region:
    external: true
  blog_aws_access_key_id:
    external: true
  blog_aws_secret_access_key:
    external: true

volumes:
  blog_db:

networks:
  ip812_network:
    driver: overlay
    attachable: true

