---
services:
  go-indie-hacking-starter:
    image: 678468774710.dkr.ecr.eu-west-2.amazonaws.com/ip812/blog:0.2.0
    ports:
      - "80:8080"
    environment:
      - APP_ADDR=localhost
      - APP_PORT=8080
      - APP_DB_FILE=go-indie-hacking-starter.db
  portainer-agent:
    image: portainer/agent:2.21.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer_agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ee:2.21.5
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
    networks:
      - portainer_agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  portainer_agent_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data:

