services:
  go-indie-hacking-starter:
    image: 678468774710.dkr.ecr.eu-west-2.amazonaws.com/ip812/blog:0.3.0
    ports:
      - "80:8080"
    environment:
      - APP_ADDR=localhost
      - APP_PORT=8080
      - APP_DB_FILE=go-indie-hacking-starter.db
