---
services:
  cloudflared:
    image: cloudflare/cloudflared:2025.1.0
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${IP812_TUNNEL_TOKEN}
    networks:
      - ip812_network
    deploy:
      mode: replicated
      replicas: 1

  traefik:
    image: "traefik:v3.2"
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--entryPoints.web.address=:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.ip812.com`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - ip812_network
    deploy:
      mode: replicated
      replicas: 1

  # litestream:
  #   image: litestream/litestream:0.3.13
  #   command: ["replicate"]
  #   volumes:
  #     - blog_db:/data:ro
  #     - /etc/litestream:/etc/litestream:ro
  #   networks:
  #     - ip812_network
  #   deploy:
  #     mode: replicated
  #     replicas: 1

  blog:
    image: iypetrov/go-indie-hacking-starter:0.10.4
    secrets:
      - blog_domain
      - blog_port
      - blog_db_file
      - blog_aws_region
      - blog_aws_access_key_id
      - blog_aws_secret_access_key
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog.rule=Host(`deviliablog.com`)"
      - "traefik.http.routers.blog.entrypoints=web"
      - "traefik.http.services.blog.loadbalancer.server.port=8080"
    volumes:
      - blog_db:/data
    networks:
      - ip812_network
    deploy:
      mode: replicated
      replicas: 1

secrets:
  blog_domain:
    external: true
  blog_port:
    external: true
  blog_db_file:
    external: true
  blog_aws_region:
    external: true
  blog_aws_access_key_id:
    external: true
  blog_aws_secret_access_key:
    external: true

volumes:
  blog_db:

networks:
  ip812_network:
    driver: overlay
    attachable: true
