services:
  go-indie-hacking-starter:
    image: iypetrov/go-indie-hacking-starter:0.1.0
    ports:
      - "80:8080"
    environment:
      - APP_ADDR=localhost
      - APP_PORT=8080
      - APP_DB_FILE=go-indie-hacking-starter.db
