---
services:
  cloudflared:
    image: cloudflare/cloudflared:2024.12.2
    command: tunnel run
    environment:
      - TUNNEL_ID=388fbc6c-66f6-4f19-bafd-150a0fa85ac6
      - TUNNEL_TOKEN=${IP812_TUNNEL_TOKEN}
    networks:
      - ip812_network

  traefik:
    image: "traefik:v3.2"
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.websecure.forwardedHeaders.insecure=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.deviliablog.com`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - ip812_network

  portainer:
    image: portainer/portainer-ce:2.25.1
    command: -H unix:///var/run/docker.sock
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.deviliablog.com`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ip812_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  blog:
    image: iypetrov/go-indie-hacking-starter:0.9.2
    secrets:
      - blog_domain
      - blog_port
      - blog_db_file
      - blog_aws_region
      - blog_aws_access_key_id
      - blog_aws_secret_access_key
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog.rule=Host(`deviliablog.com`)"
      - "traefik.http.routers.blog.entrypoints=web"
      - "traefik.http.services.blog.loadbalancer.server.port=8080"
    networks:
      - ip812_network

secrets:
  blog_domain:
    external: true
  blog_port:
    external: true
  blog_db_file:
    external: true
  blog_aws_region:
    external: true
  blog_aws_access_key_id:
    external: true
  blog_aws_secret_access_key:
    external: true

networks:
  ip812_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data:
