---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale-cleanup-stale-devices
  namespace: flux-system
spec:
  interval: 60m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./envs/prod/tailscale-cleanup-stale-devices
  prune: true
  wait: true
  timeout: 2m
  dependsOn:
    - name: doppler
      namespace: flux-system
