---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale
  namespace: flux-system
spec:
  interval: 60s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./envs/prod/tailscale
  prune: true
  wait: true
  dependsOn:
    - name: tailscale-cleanup-stale-devices
      namespace: flux-system
