---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- secret.yaml
- helmrepository.yaml
- helmrelease.yaml
configMapGenerator:
  - name: pgadmin-values
    namespace: database 
    options:
      disableNameSuffixHash: true
    files:
      - values.yaml=../../values/pgadmin.yaml
