---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: capacitor
  namespace: flux-system
spec:
  interval: 12h
  url: oci://ghcr.io/gimlet-io/capacitor-manifests
  ref:
    semver: ">=0.1.0"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capacitor-oci
  namespace: flux-system
spec:
  interval: 10m
  path: ./
  prune: true
  sourceRef:
    kind: OCIRepository
    name: capacitor
  wait: true
  patches:
    - patch: |
        - op: add
          path: /metadata/annotations/tailscale.com~1expose
          value: "true"
      target:
        kind: Service
        name: capacitor
    - patch: |
        - op: add
          path: /metadata/annotations/tailscale.com~1hostname
          value: "capacitor"
      target:
        kind: Service
        name: capacitor
    - patch: |
        - op: replace
          path: /spec/ports/0/port
          value: 80
      target:
        kind: Service
        name: capacitor
    - patch: |
        - op: add
          path: /spec/ports/0/targetPort
          value: 9000
      target:
        kind: Service
        name: capacitor
