---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger
  namespace: tracing
spec:
  interval: 5m
  chart:
    spec:
      chart: jaeger
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
      interval: 60m
  valuesFrom:
    - kind: ConfigMap
      name: jaeger-values
