name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
        contents: read
        packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to ECR
      id: ecr
      uses: jwalton/gh-ecr-login@v3
      with:
        region: ${{ secrets.AWS_REGION }}
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Get ECR Registry Token
      id: ecr-token
      run: |
        echo "REGISTRY_TOKEN=$(aws ecr get-login-password --region ${{ secrets.AWS_REGION }})" >> $GITHUB_ENV

    - name: Deploy
      uses: serversideup/github-action-docker-swarm-deploy@v3
      with:
        docker_compose_file_path: "-c prod/docker-stack.yml"
        ssh_deploy_private_key: "${{ secrets.SSH_PRIVATE_KEY }}"
        ssh_remote_hostname: "${{ secrets.HOSTNAME }}"
        registry-username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        registry-token: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        stack_name: "ip812"
        ssh_deploy_user: "ubuntu"
        registry: ${{ steps.ecr.outputs.account }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
