---
name: Deploy 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        env:
          ORG: ${{ secrets.ORG }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          set -e 

          INSTANCE_ID=$(aws ec2 describe-instances \
            --region "${AWS_REGION}" \
            --filters "Name=tag:Environment,Values=prod" "Name=tag:Organization,Values=${ORG}" \
            --query "Reservations[].Instances[].InstanceId" \
            --output json | jq -r '.[]' | head -n 1)

          if [[ -z "${INSTANCE_ID}" ]]; then
            echo "Error: No instance found matching the given filters."
            exit 1
          fi
          echo "HA instance ID: ${INSTANCE_ID}"

          CMD="export CF_TUNNEL_TOKEN=${{ secrets.CF_TUNNEL_TOKEN }} && \
               curl -H 'Authorization: token ${{ secrets.GH_ACCESS_TOKEN }}' -s https://raw.githubusercontent.com/${{ github.repository }}/main/prod/docker-stack.yml | \
               docker stack deploy -c - ${{ secrets.ORG }} --with-registry-auth"
          .github/scripts/aws-ssm-exec-cmd-on-ec2.sh "${CMD}" "${INSTANCE_ID}"

          sleep 10

          CMD="docker service ls --format '{{.Image}} {{.Replicas}}'"
          .github/scripts/aws-ssm-exec-cmd-on-ec2.sh "${CMD}" "${INSTANCE_ID}" > deploy_result.txt

      - name: Upload result artifact of "Deploy" job
        uses: actions/upload-artifact@v4
        with:
          name: deploy-result
          path: deploy_result.txt

  discord-notification:
    runs-on: ubuntu-24.04
    needs: deploy
    if: ${{ always() }}
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Download result artifact from "Deploy" job
        uses: actions/download-artifact@v4
        if: ${{ needs.deploy.result == 'success' }}
        with:
          name: deploy-result
  
      - name: Send notification to Discord's deployments channel
        run: |
          set -e

          ENV="prod"
          COMMIT_LINK="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          ACTION_LINK="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          if [[ "${{ needs.deploy.result }}" != "success" ]]; then
            TITLE="Deployment"
            DESCRIPTION="The deployment job **failed**."
            STATUS="failure"
            FIELDS="$([ "${{ github.event_name }}" = "workflow_dispatch" ] && echo "Environment=${ENV},Action=${ACTION_LINK}" || echo "Environment=${ENV},Commit=${COMMIT_LINK},Action=${ACTION_LINK}")"
            DISCORD_DEPLOYMENTS_WEBHOOK_URL=${{ secrets.DISCORD_DEPLOYMENTS_WEBHOOK_URL }}
            .github/scripts/send-discord-notification.sh "${TITLE}" "${DESCRIPTION}" "${STATUS}" "${FIELDS}" "${DISCORD_DEPLOYMENTS_WEBHOOK_URL}"
            exit 0
          fi
  
          CNT=0
          RESULT="$(mktemp)"
          while read LINE; do
            [[ -z "${LINE}" ]] && continue

            CNT=$((CNT + 1))

            IMAGE="$(echo "${LINE}" | cut -d ' ' -f 1)" 
            REPLICAS="$(echo "${LINE}" | cut -d ' ' -f 2)" 
            echo "Image: ${IMAGE}"
            echo "Replicas: ${REPLICAS}"

            if [[ "${REPLICAS}" != "1/1" ]]; then 
                printf "${IMAGE}, " >> "${RESULT}"
            fi
          done < <(cat deploy_result.txt)

          # If there are 0 services to deploy, something went wrong
          if [[ ${CNT} -eq 0 ]]; then
            TITLE="Deployment"
            DESCRIPTION="**0 services** are running after the deployment."
            STATUS="failure"
            FIELDS="$([ "${{ github.event_name }}" = "workflow_dispatch" ] && echo "Environment=${ENV},Action=${ACTION_LINK}" || echo "Environment=${ENV},Commit=${COMMIT_LINK},Action=${ACTION_LINK}")"
            DISCORD_DEPLOYMENTS_WEBHOOK_URL=${{ secrets.DISCORD_DEPLOYMENTS_WEBHOOK_URL }}
            .github/scripts/send-discord-notification.sh "${TITLE}" "${DESCRIPTION}" "${STATUS}" "${FIELDS}" "${DISCORD_DEPLOYMENTS_WEBHOOK_URL}"
            exit 0
          fi

          # Remove the ", " at the end
          if [[ -s "${RESULT}"  ]]; then
              cat "${RESULT}" | rev | cut -c3- | rev > "${RESULT}"
          fi
          echo "Failing services:" 
          cat "${RESULT}" 

          # Count the number of failing services
          CNT_FAILING_SERVICES=$(echo "${RESULT}" | tr -cd ',' | wc -c)
          echo "Number of failing services: ${CNT_FAILING_SERVICES}" 

          if [[ -s "${RESULT}"  ]]; then
            TITLE="Deployment"
            DESCRIPTION="The deployment was **successful**."
            STATUS="success"
            FIELDS="$([ "${{ github.event_name }}" = "workflow_dispatch" ] && echo "Environment=${ENV},Action=${ACTION_LINK}" || echo "Environment=${ENV},Commit=${COMMIT_LINK},Action=${ACTION_LINK}")"
            DISCORD_DEPLOYMENTS_WEBHOOK_URL=${{ secrets.DISCORD_DEPLOYMENTS_WEBHOOK_URL }}
            .github/scripts/send-discord-notification.sh "${TITLE}" "${DESCRIPTION}" "${STATUS}" "${FIELDS}" "${DISCORD_DEPLOYMENTS_WEBHOOK_URL}"
          else
            TITLE="Deployment"
            DESCRIPTION="**${CNT_FAILING_SERVICES} services** failed after deployment."
            STATUS="failure"
            FIELDS="$([ "${{ github.event_name }}" = "workflow_dispatch" ] && echo "Environment=${ENV},Action=${ACTION_LINK}" || echo "Environment=${ENV},Commit=${COMMIT_LINK},Action=${ACTION_LINK}")"
            DISCORD_DEPLOYMENTS_WEBHOOK_URL=${{ secrets.DISCORD_DEPLOYMENTS_WEBHOOK_URL }}
            .github/scripts/send-discord-notification.sh "${TITLE}" "${DESCRIPTION}" "${STATUS}" "${FIELDS}" "${DISCORD_DEPLOYMENTS_WEBHOOK_URL}"
          fi

