---
name: Prod K8s Apply

on:
  push:
    branches:
      - main
    paths:
      - "manifests/prod/**"
      - "values/**"

jobs:
  k8s-apply:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Checkout toolkit
        uses: actions/checkout@v5
        with:
          repository: ip812/toolkit
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          path: toolkit

      - name: Pull & apply latest changes
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          set -e 

          INSTANCE_ID=$(aws ec2 describe-instances \
            --region "${AWS_REGION}" \
            --filters \
              "Name=tag:Environment,Values=prod" \
              "Name=tag:Organization,Values=${{ vars.ORG }}" \
              "Name=instance-state-name,Values=running" \
            --query "Reservations[].Instances[].InstanceId" \
            --output json | jq -r '.[]' | head -n 1)

          if [[ -z "${INSTANCE_ID}" ]]; then
            echo "Error: No instance found matching the given filters."
            exit 1
          fi
          echo "HA instance ID: ${INSTANCE_ID}"

          CMD="git -C /apps reset --hard && git -C /apps clean -fd && git -C /apps pull"
          touch pull_result.txt
          toolkit/scripts/aws-ssm-exec-cmd-on-ec2.sh "${CMD}" "${INSTANCE_ID}" pull_result.txt

          CMD="k0s kubectl apply -k /apps/manifests/prod"
          touch apply_result.txt
          toolkit/scripts/aws-ssm-exec-cmd-on-ec2.sh "${CMD}" "${INSTANCE_ID}" apply_result.txt
